apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}-deployment
  ports:
    - port: {{.Values.servicePort}}
      targetPort: {{.Values.targetPort}}