common:
  containerRegistryURL: tododevacr1.azurecr.io
  ingressClass: azure-application-gateway
ui:
  Name: todo-ui
  replicas: 1
  image:
    name: todo-ui
    tag: v1
  port: 80
  ServicePort: 80
  ingress:
    host: ui.jhandu.shop
    # ingressClass: azure-application-gateway

getTask:
  Name: gettask
  replicas: 1
  image:
    name: todo-get-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:mssql-svc.default.svc.cluster.local,1433;Database=mydb;Uid=sa;Pwd=admin@123;Encrypt=no;TrustServerCertificate=yes;Connection Timeout=30;"
  ingress:
    host: get-tasks-api.jhandu.shop
    ingressClass: azure-application-gateway

deleteTask:
  Name: deletetask
  replicas: 1
  image:
    name: todo-delete-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:mssql-svc.default.svc.cluster.local,1433;Database=mydb;Uid=sa;Pwd=admin@123;Encrypt=no;TrustServerCertificate=yes;Connection Timeout=30;"
  ingress:
    host: delete-task-api.jhandu.shop
    ingressClass: azure-application-gateway

addTask:
  Name: addtask
  replicas: 1
  image:
    name: todo-add-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:mssql-svc.default.svc.cluster.local,1433;Database=mydb;Uid=sa;Pwd=admin@123;Encrypt=no;TrustServerCertificate=yes;Connection Timeout=30;"
  ingress:
    host: add-task-api.jhandu.shop
    ingressClass: azure-application-gateway

